// Generated by gencpp from file arm_gazebo/Angles.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_ANGLES_H
#define ARM_GAZEBO_MESSAGE_ANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct Angles_
{
  typedef Angles_<ContainerAllocator> Type;

  Angles_()
    : base_hinge(0.0)
    , arm1_hinge(0.0)
    , arm2_hinge(0.0)
    , arm3_hinge(0.0)  {
    }
  Angles_(const ContainerAllocator& _alloc)
    : base_hinge(0.0)
    , arm1_hinge(0.0)
    , arm2_hinge(0.0)
    , arm3_hinge(0.0)  {
  (void)_alloc;
    }



   typedef float _base_hinge_type;
  _base_hinge_type base_hinge;

   typedef float _arm1_hinge_type;
  _arm1_hinge_type arm1_hinge;

   typedef float _arm2_hinge_type;
  _arm2_hinge_type arm2_hinge;

   typedef float _arm3_hinge_type;
  _arm3_hinge_type arm3_hinge;





  typedef boost::shared_ptr< ::arm_gazebo::Angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::Angles_<ContainerAllocator> const> ConstPtr;

}; // struct Angles_

typedef ::arm_gazebo::Angles_<std::allocator<void> > Angles;

typedef boost::shared_ptr< ::arm_gazebo::Angles > AnglesPtr;
typedef boost::shared_ptr< ::arm_gazebo::Angles const> AnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::Angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::Angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::Angles_<ContainerAllocator1> & lhs, const ::arm_gazebo::Angles_<ContainerAllocator2> & rhs)
{
  return lhs.base_hinge == rhs.base_hinge &&
    lhs.arm1_hinge == rhs.arm1_hinge &&
    lhs.arm2_hinge == rhs.arm2_hinge &&
    lhs.arm3_hinge == rhs.arm3_hinge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::Angles_<ContainerAllocator1> & lhs, const ::arm_gazebo::Angles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::Angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::Angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::Angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::Angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::Angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::Angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebea2e1e660d8f6f3597c7be6738767c";
  }

  static const char* value(const ::arm_gazebo::Angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebea2e1e660d8f6fULL;
  static const uint64_t static_value2 = 0x3597c7be6738767cULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/Angles";
  }

  static const char* value(const ::arm_gazebo::Angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 base_hinge\n"
"float32 arm1_hinge\n"
"float32 arm2_hinge\n"
"float32 arm3_hinge\n"
;
  }

  static const char* value(const ::arm_gazebo::Angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::Angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_hinge);
      stream.next(m.arm1_hinge);
      stream.next(m.arm2_hinge);
      stream.next(m.arm3_hinge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::Angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::Angles_<ContainerAllocator>& v)
  {
    s << indent << "base_hinge: ";
    Printer<float>::stream(s, indent + "  ", v.base_hinge);
    s << indent << "arm1_hinge: ";
    Printer<float>::stream(s, indent + "  ", v.arm1_hinge);
    s << indent << "arm2_hinge: ";
    Printer<float>::stream(s, indent + "  ", v.arm2_hinge);
    s << indent << "arm3_hinge: ";
    Printer<float>::stream(s, indent + "  ", v.arm3_hinge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_ANGLES_H
