// Generated by gencpp from file arm_gazebo/ikServiceRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKSERVICEREQUEST_H
#define ARM_GAZEBO_MESSAGE_IKSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct ikServiceRequest_
{
  typedef ikServiceRequest_<ContainerAllocator> Type;

  ikServiceRequest_()
    : links()
    , ee()  {
    }
  ikServiceRequest_(const ContainerAllocator& _alloc)
    : links(_alloc)
    , ee(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _links_type;
  _links_type links;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _ee_type;
  _ee_type ee;





  typedef boost::shared_ptr< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ikServiceRequest_

typedef ::arm_gazebo::ikServiceRequest_<std::allocator<void> > ikServiceRequest;

typedef boost::shared_ptr< ::arm_gazebo::ikServiceRequest > ikServiceRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::ikServiceRequest const> ikServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::ikServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::ikServiceRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.links == rhs.links &&
    lhs.ee == rhs.ee;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::ikServiceRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a398fe782f9e2bda9eafa35909ec68";
  }

  static const char* value(const ::arm_gazebo::ikServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a398fe782f9e2bULL;
  static const uint64_t static_value2 = 0xda9eafa35909ec68ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/ikServiceRequest";
  }

  static const char* value(const ::arm_gazebo::ikServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] links\n"
"float32[] ee\n"
;
  }

  static const char* value(const ::arm_gazebo::ikServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.links);
      stream.next(m.ee);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::ikServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::ikServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "links[]" << std::endl;
    for (size_t i = 0; i < v.links.size(); ++i)
    {
      s << indent << "  links[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.links[i]);
    }
    s << indent << "ee[]" << std::endl;
    for (size_t i = 0; i < v.ee.size(); ++i)
    {
      s << indent << "  ee[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ee[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKSERVICEREQUEST_H
