// Generated by gencpp from file arm_gazebo/ikServiceResponse.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKSERVICERESPONSE_H
#define ARM_GAZEBO_MESSAGE_IKSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct ikServiceResponse_
{
  typedef ikServiceResponse_<ContainerAllocator> Type;

  ikServiceResponse_()
    : angles()  {
    }
  ikServiceResponse_(const ContainerAllocator& _alloc)
    : angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ikServiceResponse_

typedef ::arm_gazebo::ikServiceResponse_<std::allocator<void> > ikServiceResponse;

typedef boost::shared_ptr< ::arm_gazebo::ikServiceResponse > ikServiceResponsePtr;
typedef boost::shared_ptr< ::arm_gazebo::ikServiceResponse const> ikServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::ikServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::ikServiceResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::ikServiceResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7ca77b9da2dfe623a276e10b570d2df";
  }

  static const char* value(const ::arm_gazebo::ikServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7ca77b9da2dfe62ULL;
  static const uint64_t static_value2 = 0x3a276e10b570d2dfULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/ikServiceResponse";
  }

  static const char* value(const ::arm_gazebo::ikServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] angles\n"
"\n"
;
  }

  static const char* value(const ::arm_gazebo::ikServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::ikServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::ikServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKSERVICERESPONSE_H
